### PR TITLE
Create kimcartoon.li.js

### PR DESCRIPTION
**Pull request by OshekharO**
Search broken, I don't have any idea how to fix either 🤧 @MiaoMint please look into this.

### CODE REVIEW

**Comment by MiaoMint** [comment]
I'll try

**Comment by MiaoMint** [comment]
```js
   const res = await this.request("", {
      headers: {
        "Miru-Url": "https://kimcartoon.li/Search/Cartoon",
        "Content-Type": "application/x-www-form-urlencoded",
      },
      data: {
        keyword: kw,
      },
      method: "Post",
    });
```

Content-Type should be  `application/x-www-form-urlencoded`

**Comment by OshekharO** [comment]
> ```js
>    const res = await this.request("", {
>       headers: {
>         "Miru-Url": "https://kimcartoon.li/Search/Cartoon",
>         "Content-Type": "application/x-www-form-urlencoded",
>       },
>       data: {
>         keyword: kw,
>       },
>       method: "Post",
>     });
> ```
> 
> Content-Type should be `application/x-www-form-urlencoded`

Still same issue 302 or no more data

**Comment by MiaoMint** [comment]
> > ```js
> >    const res = await this.request("", {
> >       headers: {
> >         "Miru-Url": "https://kimcartoon.li/Search/Cartoon",
> >         "Content-Type": "application/x-www-form-urlencoded",
> >       },
> >       data: {
> >         keyword: kw,
> >       },
> >       method: "Post",
> >     });
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Content-Type should be `application/x-www-form-urlencoded`
> 
> Still same issue 302 or no more data

I tested everything fine

**Comment by OshekharO** [comment]
> > > ```js
> > >    const res = await this.request("", {
> > >       headers: {
> > >         "Miru-Url": "https://kimcartoon.li/Search/Cartoon",
> > >         "Content-Type": "application/x-www-form-urlencoded",
> > >       },
> > >       data: {
> > >         keyword: kw,
> > >       },
> > >       method: "Post",
> > >     });
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Content-Type should be `application/x-www-form-urlencoded`
> > 
> > 
> > Still same issue 302 or no more data
> 
> I tested everything fine

Oh yeah I changed selectors value that's why it was showing no more data

**Pull request merged**
