### PR TITLE
Create sxyprn.js

### PR DESCRIPTION
**Pull request by OshekharO**
@MiaoMint bro can you check watch section and details why is vid link not being fetch

### CODE REVIEW

**Comment by OshekharO** [comment]
@821938089 any idea what went wrong?

**Comment by MiaoMint** [comment]
I'll deal with it later

**Comment by OshekharO** [comment]
> I'll deal with it later

Sure

**Comment by MiaoMint** [comment]
I can't seem to find the playback link in the html

**Comment by OshekharO** [comment]
> I can't seem to find the playback link in the html

Here 

video id='player_el' class='player_el player_el_nc' data-postid='64f1edf1070a1' src='' poster='//s19.trafficdeposit.com/blog/img/636df919c9f5f/64f1edf1070a1/0.jpg' controls> video>

**Comment by MiaoMint** [comment]
> Here
> 
> video id='player_el' class='player_el player_el_nc' data-postid='64f1edf1070a1' src='' poster='//s19.trafficdeposit.com/blog/img/636df919c9f5f/64f1edf1070a1/0.jpg' controls> video>

this is just a picture

**Comment by OshekharO** [comment]
> > Here
> > video id='player_el' class='player_el player_el_nc' data-postid='64f1edf1070a1' src='' poster='//s19.trafficdeposit.com/blog/img/636df919c9f5f/64f1edf1070a1/0.jpg' controls> video>
> 
> this is just a picture

No do inspect element on player you will see the link at src=''

**Comment by MiaoMint** [comment]
I can't find the playback link in his html text, it should be encrypted.

**Comment by OshekharO** [comment]
> I can't find the playback link in his html text, it should be encrypted.



Here it's

**Comment by MiaoMint** [comment]
This is the link that the site gets by manipulating the DOM, miru doesn't have a DOM, you need to find a way to get the playback links

**Comment by OshekharO** [comment]
> This is the link that the site gets by manipulating the DOM, miru doesn't have a DOM, you need to find a way to get the playback links

Then I don't think it's going to work or you can check if it's going to work with class vidsnfo. Check the bottom of above img

**Pull request closed without merging**
