### PR TITLE
Added "Preferred quality" option

### PR DESCRIPTION
**Pull request by ancientcatz**

### CODE REVIEW

**Comment by OshekharO** [comment]
LGTM, just tested working fine.

**Review by OshekharO — APPROVED** [review]

**Comment by ancientcatz** [comment]
> LGTM, just tested working fine.

With this I can sleep soundly

**Comment by MiaoMint** [comment]
@AncientCatz  The version number is not updated

**Comment by ancientcatz** [comment]
> @AncientCatz The version number is not updated

Sorry about that, I just realized that too. I'll upgrade the version.

**Pull request merged**
