### PR TITLE
Create invidious.io

### PR DESCRIPTION
**Pull request by OshekharO**
Audio and video both are seperated since there is no option for audio tracks , I don't know how to add it also subtitle are not able to open. You can merge if video only is not an issue.

Api docs with json schema for stream api: https://piped-docs.kavin.rocks/docs/api-documentation/

### CODE REVIEW

**Comment by MiaoMint** [comment]
I didn't think about the split track at first

**Comment by MiaoMint** [comment]
Try https://github.com/miru-project/miru-app/pull/72

`audioTrack` field

**Comment by OshekharO** [comment]
> Try [miru-project/miru-app#72](https://github.com/miru-project/miru-app/pull/72)
> 
> `audioTrack` field

Already added but where is the build with audio changes merged?

**Comment by OshekharO** [comment]
> Try [miru-project/miru-app#72](https://github.com/miru-project/miru-app/pull/72)
> 
> `audioTrack` field

Screenshot_2023-09-21-08-51-21-27_724c77a6924735f59ad9bef5bae520c3

No option for audio track in player, tried latest build

**Comment by MiaoMint** [comment]
The type of audioTrack is string

**Comment by OshekharO** [comment]
> The type of audioTrack is string

Have tried this still not working showing type error not a function at watch

audioTrack: res.audioStreams[0].map((item) => item.url),


This also not working

audioTrack: res.audioStreams[0]?.url || "",

**Comment by MiaoMint** [comment]
image
I can't open the video.

**Comment by OshekharO** [comment]
> image I can't open the video.

Go back and open again it will work

**Comment by MiaoMint** [comment]
> > The type of audioTrack is string
> 
> Have tried this still not working showing type error not a function at watch
> 
> audioTrack: res.audioStreams[0].map((item) => item.url),
> 
> This also not working
> 
> audioTrack: res.audioStreams[0]?.url || "",

In the latest commit, my test has been working normally, but this extension always needs to be opened multiple times, otherwise access will fail.

**Comment by OshekharO** [comment]
audioTrack field will be

audioTrack: res.audioStreams?.[0]?.url,

right?

**Comment by MiaoMint** [comment]
> audioTrack field will be
> 
> audioTrack: res.audioStreams?.[0]?.url,
> 
> right? Or below one?
> 
> const track = res.audioStreams.map((item) => ({ title: item.format, url: item.url, language: item.quality, }));

Just one, type is string

**Comment by MiaoMint** [comment]
It should work fine, right?

**Comment by OshekharO** [comment]
LGTM

**Pull request merged**
