### PR TITLE
Fixed bugs about global search

### PR DESCRIPTION
**Pull request by hualiong**
feisuzy.com and to-long.com are no longer active, so I have removed them.

And I add www.Iwara.tv, even though Miru is unable to play the link of videos on this website.

However, you can close issue #293 first.

### CODE REVIEW

**Comment by OshekharO** [comment]
@hualiong why adding Iwara of the videos cannot be played??

**Comment by hualiong** [comment]
> @hualiong why adding Iwara of the videos cannot be played??↳

I guess this is a Miru Bug because I can download and play those links normally with the local player.

But Miru couldn't open those links.

image

image

**Comment by ijs77** [comment]
> > @hualiong why adding Iwara of the videos cannot be played??↳
> 
> I guess this is a Miru Bug because I can download and play those links normally with the local player.
> 
> But Miru couldn't open those links.
> 
> image
> 
> image

work for me 

image

**Comment by hualiong** [comment]
> > > @hualiong why adding Iwara of the videos cannot be played??↳↳
> > 
> > 
> > I guess this is a Miru Bug because I can download and play those links normally with the local player.↳
> > But Miru couldn't open those links.↳
> > image
> > image
> 
> work for me↳
> 
> image

All right, maybe it's due to my network problem

**Pull request merged**
