### PR TITLE
Create yomovies.js

### PR DESCRIPTION
**Pull request by OshekharO**
Watch broken need to be fixed

### CODE REVIEW

**Comment by OshekharO** [comment]
Ahh to get the stream link from minoplres we have to put these in request body 

op=download1&usr_login=Batman&id=xuux88qvc2rd&referer=https%3A%2F%2Fyomovies.makeup%2F&hash=27331-10-26-1696225175-8a4b2f3f64b64bb87afdf05d92fdefe9&imhuman=Proceed+to+video

Everything is okay but I don't understand where is this hash coming from please check it @MiaoMint 

Okk i got it for example https://minoplres.xyz/xuux88qvc2rd.html when we put request value to op=download1&usr_login=Batman&referer=https%3A%2F%2Fyomovies.makeup%2F&imhuman=Proceed+to+video

We get in response this 

https://pastebin.com/raw/E9q2LqmM

But still I don't know how to make it work 😑

**Comment by OshekharO** [comment]
Here is the modified watch section by me but still not working

https://pastebin.com/raw/9bGwkbgt

Or

https://pastebin.com/raw/uZ8xMGu1

**Comment by MiaoMint** [comment]
You can try debugging it in postman before writing it or it's a bit of a pain in the ass.

**Comment by OshekharO** [comment]
> You can try debugging it in postman before writing it or it's a bit of a pain in the ass.

I tried all I get is

https://pastebin.com/raw/HEs98uEz

Looks like This not gonna work.

**Comment by OshekharO** [comment]
Hard to extract source link so closing this pr

**Pull request closed without merging**
