### PR TITLE
Create extension

### PR DESCRIPTION
**Pull request by OshekharO**
Need to fix watch section

Chapter can be found at https://api.mtlnation.com/api/v2/chapters/all-people-what-do-you-call-gm-a-life-profession/chapter-1-awakening-season-abandoned-dual-career

It should be something like this please check 

/api/v2/chapters/${url}/${url}

If possible also add

"https://api.mtlnation.com/api/v2/accounts/login",
            data=json.dumps(
                {
                    "identity": email,
                    "password": password,
                }
            ),

jwt = self.cookies.get("jwt")
        self.set_header("authorization", f"JWT {jwt}")

Then set headers Authorization to jwt maybe?

### CODE REVIEW

**Comment by OshekharO** [comment]
@MiaoMint check watch section once I am getting confused

**Comment by MiaoMint** [comment]
https://codeshare.io/zyLgW7

**Comment by OshekharO** [comment]
> https://codeshare.io/zyLgW7

Authorization thing can be done ? Or let's ignore for now?

**Comment by MiaoMint** [comment]
Maybe make a setting that fills in the cookie

**Comment by OshekharO** [comment]
LGTM @MiaoMint

**Pull request merged**
