### PR TITLE
update 0.0.2

### PR DESCRIPTION
**Pull request by vvsolo**
更新：
1、更名 `MyIPTV`
2、修改 `webSite`、`icon`
3、内置几个可用的源
4、可解析 m3u 和 txt 格式
5、添加筛选功能
6、多源地址分隔

建议：
1、若扩展有设置选项，能否在界面加个图标跳转
2、头部加入 `@tmdb` 开关

### CODE REVIEW

**Comment by OshekharO** [comment]
@vvsolo have you tested properly? 自定义源 not working only default source showing not able to.use iptv-org.

**Comment by bachig26** [comment]
@OshekharO @vvsolo can you also add these iptv here if possible?
Japanese TV's: https://github.com/luongz/iptv-jp
meWatch Singapore IPTV: https://github.com/samleong123/mewatchsg
Thai Public TV's: https://github.com/akkradet/IPTV-THAI
Turkish TV's: https://github.com/keyiflerolsun/IPTV_YenirMi
German Public TV's: https://github.com/josxha/german-tv-m3u

**Comment by vvsolo** [comment]
> @vvsolo have you tested properly? 自定义源 not working only default source showing not able to.use iptv-org.

iptv-org 测试过，但如果源内容太多，解析会很慢...
you can test `iptv-org-country-kr`.
`iptv-org-category-movies` too many lines, parse to slow...

**Comment by vvsolo** [comment]
> @OshekharO @vvsolo can you also add these iptv here if possible? Japanese TV's: https://github.com/luongz/iptv-jp meWatch Singapore IPTV: https://github.com/samleong123/mewatchsg Thai Public TV's: https://github.com/akkradet/IPTV-THAI Turkish TV's: https://github.com/keyiflerolsun/IPTV_YenirMi German Public TV's: https://github.com/josxha/german-tv-m3u

此次更新不用合并了
你发的地址格式不一样，代码要修改

**Comment by OshekharO** [comment]
> > @vvsolohave you tested properly? 自定义源 not working only default source showing not able to.use iptv-org.
> 
> iptv-org has tested it, but if there is too much source content, parse will be very slow... you can test `iptv-org-country-kr`. `iptv-org-category-movies`too many lines, parse to slow...

Screenshot_2024-01-01-19-27-59-84_724c77a6924735f59ad9bef5bae520c3

I am getting this error in eny of iptv-org sources.

**Comment by vvsolo** [comment]
> > > @vvsolohave you tested properly? 自定义源 not working only default source showing not able to.use iptv-org.
> > 
> > 
> > iptv-org has tested it, but if there is too much source content, parse will be very slow... you can test `iptv-org-country-kr`. `iptv-org-category-movies`too many lines, parse to slow...
> 
> Screenshot_2024-01-01-19-27-59-84_724c77a6924735f59ad9bef5bae520c3
> 
> I am getting this error in eny of iptv-org sources.

iptv-org-country-hk 可以显示
iptv-org-country-cn 1300多行，读取很慢
null 可能是格式读取错误，我已经修改...

**Comment by OshekharO** [comment]
Alright remove all other sources which are not working or modify the code accordingly.

**Comment by vvsolo** [comment]
@bachig26 
Japanese TV's: √
meWatch Singapore IPTV: × encryption format
Thai Public TV's: √
Turkish TV's: √
German Public TV's: √

**Comment by bachig26** [comment]
> meWatch Singapore IPTV: × encryption format

@OshekharO @MiaoMint @appdevelpo is it possible to add an widevine module/function to support this encryption?

Edit: possibly using similar to this? https://pub.dev/packages/better_player

**Pull request merged**
