### PR TITLE
Comick Extension

### PR DESCRIPTION
**Pull request by OshekharO**

### CODE REVIEW

**Comment by OshekharO** [comment]
@MiaoMint please check watch and detail section , as for documentation you can refer to tmdb docs, it will be bonus if you can add support for anime and series also in this by doing something like type = isSeries ? "tv" : "movie";

I don't know that much so I was not able to implement it.

**Comment by OshekharO** [comment]
Still I got no solution for streaming 😐 tried various ways but none worked.

**Comment by OshekharO** [comment]
In Comick needs fix in detail section for fetching chapter's and watch section.

Docs: https://api.comick.fun/docs/static/index.html

Refer: https://github.com/manga-download/hakuneko/blob/master/src/web/mjs/connectors/ComicK.mjs#L23

@MiaoMint

**Comment by OshekharO** [comment]
With this changes it's showing chapters https://pastebin.com/ra3BtXTt but not all chapters are being shown also some chapters returning null title.

This too work : const epRes = await this.req(`/comic/${hid}/chapters?lang=en&chap-order=1`);

Chapter null fixed but missing chapters coming 😕

episodes: [
  {
    title: "Chapters",
    urls: epRes.chapters
      .filter((item) => item.lang === "en" && item.title !== null && item.chap !== "null")
      .map((item) => ({
        name: `Chapter ${item.chap}`,
        url: item.hid,
      })),
  },
],

**Comment by MiaoMint** [comment]
wait a minute i'll try

**Comment by OshekharO** [comment]
> wait a minute i'll try

Hmm and also check if something can be done with Superembed or i should remove it

**Comment by MiaoMint** [comment]
Maybe `item.chap` should be used?

**Comment by MiaoMint** [comment]
This can support multiple languages https://pastebin.com/kvTQ1STA

**Comment by OshekharO** [comment]
> This can support multiple languages https://pastebin.com/kvTQ1STA

Hmm but still it's not showing all the chapters and watch section need to be fixed

**Review by Truimo — APPROVED** [review]
yea

**Review by Truimo — APPROVED** [review]
yea

**Comment by OshekharO** [comment]
Ok not all chapters showing i fixed let me update the code but still need fixes in watch section

**Comment by OshekharO** [comment]
Now remain watch section for comick and detail and watch section for Superembed

**Comment by OshekharO** [comment]
https://api.comick.app/chapter/y50kP?tachiyomi=true

Source images

**Comment by OshekharO** [comment]
Okk i fixed the watch section please check Superembed once as I am not able to fix that extension, should I remove it?

**Comment by MiaoMint** [comment]
> Okk i fixed the watch section please check Superembed once as I am not able to fix that extension, should I remove it?

Wait

**Comment by MiaoMint** [comment]
https://pastebin.com/2jxYTQ0L

**Comment by OshekharO** [comment]
Need to update watch section so it can support playback by both movie and series

Request movie by TMDB id: https://multiembed.mov/directstream.php?video_id=447365&tmdb=1

Request episode ( series ) by TMDB id: https://multiembed.mov/directstream.php?video_id=114472&tmdb=1&s=1&e=2

Or we can just make it movie only or series only type if not possible

**Comment by OshekharO** [comment]
Also when I tested your updated code it's giving me invalid status code 400 error

**Comment by MiaoMint** [comment]
https://pastebin.com/RkqBZNg5

**Comment by MiaoMint** [comment]
I don't how to fix the watch

**Comment by OshekharO** [comment]
Merge it I have removed that extension.

**Review by MiaoMint — APPROVED** [review]

**Pull request merged**
