### PR TITLE
Feat(add): domain options - flimypujab

### PR DESCRIPTION
**Pull request by OshekharO**
@appdevelpo can you cross verify that everything is working?

### CODE REVIEW

**Comment by appdevelpo** [comment]
image
I got a video player error?

**Comment by appdevelpo** [comment]
The video on the website cannot be loaded too.

**Comment by OshekharO** [comment]
> The video on the website cannot be loaded too.

Yes this happening with your original extension even before I started modifying

**Comment by appdevelpo** [comment]
Do have the smaple movie for testing. Almost every video on the website can't load.

**Comment by appdevelpo** [comment]
image
this is the situation of the vedio player on the site

**Comment by OshekharO** [comment]
Yes, it's an issue from their side. Maybe the cdn which is hosting the movies are down currently.

**Comment by OshekharO** [comment]
OnlineMoviesHindi
MovieMora

Are giving failed host lookup.

**Comment by OshekharO** [comment]
Closing this pr as no possible solution is available.

**Pull request closed without merging**
