### PR TITLE
Create yanaifei.tv.js

### PR DESCRIPTION
**Pull request by appdevelpo**
Need cookie to bypass cloudfare.You caan fill the blank in the extension settings.

### CODE REVIEW

**Comment by OshekharO** [comment]
Is this really good Idea? Because a normal user which occupies majority don't even know what is cookies let alone fill them manually. @MiaoMint @appdevelpo

**Comment by MiaoMint** [comment]
> Is this really good Idea? Because a normal user which occupies majority don't even know what is cookies let alone full them manually. @MiaoMint @appdevelpo

Currently, the software can not get Cloudflare cookie is a bug, can only be fixed by updating the

**Comment by appdevelpo** [comment]
I have an idea that separate an special area from normal extension. Is it plausible?

**Comment by OshekharO** [comment]
> I have an idea that separate an special area from normal extension. Is it plausible?

Can you do like this add 1 cookie by default and let user Change if that cookies expires? Even if we get a seperate area for it it's not gonna work because majority of users doesn't matter which app have no idea what is cookies.

**Comment by MiaoMint** [comment]
> I have an idea that separate an special area from normal extension. Is it plausible?

I plan to add a multi-repository feature afterwards

**Comment by OshekharO** [comment]
> > I have an idea that separate an special area from normal extension. Is it plausible?
> 
> I plan to add a multi-repository feature afterwards

Yes please categories the extension in GitHub repo also like create a folder video in which all video extensions are and so on. Also i think we should merge this, what do you think?

**Comment by appdevelpo** [comment]
> > I have an idea that separate an special area from normal extension. Is it plausible?
> 
> Can you do like this add 1 cookie by default and let user Change if that cookies expires? Even if we get a seperate area for it it's not gonna work because majority of users doesn't matter which app have no idea what is cookies.

I'll do it later

**Comment by appdevelpo** [comment]
finished.But I'm still don't understand their cloudfare blocking rule

**Comment by appdevelpo** [comment]
or I should end this pr

**Comment by OshekharO** [comment]
> finished.But I'm still don't understand their cloudfare blocking rule

Meaning? Also the code is giving me extension undefined error

**Comment by appdevelpo** [comment]
eventhough  I enter the cookie, after a while I got 403 on miru but the site didn't ask me to verify again

**Comment by appdevelpo** [comment]
ok I'll just stop this pr. I decide to ignore this extension  for a while. I spend my effort on  other extension

**Pull request closed without merging**
