### PR TITLE
added piped

### PR DESCRIPTION
**Pull request by bethropolis**

### CODE REVIEW

**Comment by OshekharO** [comment]
@bethropolis video is not stremable.

**Comment by bethropolis** [comment]
@OshekharO  it's working on all my devices




what do you mean by streamable

**Comment by bachig26** [comment]
@bethropolis piped works fine for me, except for the audio being failed to stream as you can see the error shown in the screenshot, like after 5 seconds the audio completely broke at every video that i have tried.

miru_Eayh3bq1Ty

**Comment by OshekharO** [comment]
> @OshekharO it's working on all my devices
> 
> 
> 
> what do you mean by streamable

Yes I just tried although audio is breaking sometimes it's doable but I am not able to fast forward ⏩.
Screenshot_2024-01-06-07-28-23-94_724c77a6924735f59ad9bef5bae520c3

**Comment by OshekharO** [comment]
Added extension again 👍

**Pull request merged**
