### PR TITLE
Create extension 

### PR DESCRIPTION
**Pull request by OshekharO**
Need to fix watch section

### CODE REVIEW

**Comment by OshekharO** [comment]
In gogo anime changes are to be made in watch section: https://docs.consumet.org/rest-api/Anime/gogoanime/get-anime-episode-streaming-links

And in manga18.fx ( Need to fix search and watch section )

**Comment by OshekharO** [comment]
In kisshk almost everything is good to go except for Watch Section need fix

**Comment by OshekharO** [comment]
@owocc joint contribution time 🤧 

Need fixes in manga18 and kisshk

**Comment by owocc** [comment]
> @owocc joint contribution time 🤧
> 
> Need fixes in manga18 and kisshk

ok i'll fix him lateru😄

**Comment by OshekharO** [comment]
> > @owocc joint contribution time 🤧
> > Need fixes in manga18 and kisshk
> 
> ok i'll fix him lateru😄

Hmm just create pr in https://github.com/OshekharO/repo/tree/main-2 I will merge it

**Comment by MiaoMint** [comment]
It seems that kisskh.co has encrypted the playback links

**Comment by OshekharO** [comment]
> It seems that kisskh.co has encrypted the playback links

Hmm, that's why using api thing, most of the application uses its api

https://github.com/hexated/cloudstream-extensions-hexated/blob/3b1d78858789c2036e9f088ee7b94e4cd58ccf24/KisskhProvider/src/main/kotlin/com/hexated/KisskhProvider.kt#L130

**Comment by MiaoMint** [comment]
The link was hidden here all along

image

**Comment by OshekharO** [comment]
> The link was hidden here all along
> 
> image

So now it will fetch stream right?

**Comment by OshekharO** [comment]
I was going to do this

async watch(url) {
 const res = await this.req(`/api/DramaList/Episode/${url}.png?err=false&ts=&time=`);
 
  return {
    type: "hls",
    url: res.Video,
  };
}

😂 now you can merge this pr will update manga thing later

**Comment by MiaoMint** [comment]
Ok

**Pull request merged**
