### PR TITLE
Fix cycback source

### PR DESCRIPTION
**Pull request by youyou-sudo**

### CODE REVIEW

**Comment by OshekharO** [comment]
@hualiong how is it?

**Comment by hualiong** [comment]
Let me test it.

**Comment by youyou-sudo** [comment]
It is very frustrating that just now, web.cycback.org closed
image

**Comment by hualiong** [comment]
@youyou-sudo 我有点不明白，你为啥要改这个拓展嘞？原来的拓展还能正常运行呀（直接调用接口，比解析网页还方便点）🤔

**Comment by OshekharO** [comment]
True, api is better than web parsing always use api if present.

**Comment by hualiong** [comment]
HMM.... According to the information displayed on the 'web.cycback.org' page, the site I was originally crawling to (cycanime.com) was the pirate site of the same name?

**Comment by youyou-sudo** [comment]
> @youyou-sudo 我有点不明白，你为啥要改这个拓展嘞？原来的拓展还能正常运行呀（直接调用接口，比解析网页还方便点）🤔

唉？你那边测试是可以用的吗，我这边测是失败的
image

**Comment by youyou-sudo** [comment]
> HMM.... According to the information displayed on the 'web.cycback.org' page, the site I was originally crawling to (cycanime.com) was the pirate site of the same name?

It's not piracy. I remember that cycanime.com was an early domain name used

**Comment by hualiong** [comment]
> > @youyou-sudo 我有点不明白，你为啥要改这个拓展嘞？原来的拓展还能正常运行呀（直接调用接口，比解析网页还方便点）🤔
> 
> 唉？你那边测试是可以用的吗，我这边测是失败的 image

嗯...有点奇怪。我这边PC端是正常的，手机上确实有跟你一样的问题....

**Comment by hualiong** [comment]
> > @youyou-sudo 我有点不明白，你为啥要改这个拓展嘞？原来的拓展还能正常运行呀（直接调用接口，比解析网页还方便点）🤔
> 
> 唉？你那边测试是可以用的吗，我这边测是失败的 image

嗯...有点奇怪。我这边PC端是正常的，手机上确实有跟你一样的问题....
image

**Comment by youyou-sudo** [comment]
The PR was created because nyacg.net and cycback.org have the same web template. Since web.cycback.org is closed, I will close this PR first.

**Comment by hualiong** [comment]
> The PR was created because nyacg.net and cycback.org have the same web template. Since web.cycback.org is closed, I will close this PR first.
> 
> 创建 PR 是因为 nyacg.net 和 cycback.org 具有相同的 Web 模板。 由于 web.cycback.org 已关闭，我将首先关闭此 PR。

www.cycanime.com 也关闭了，难怪有问题。不过我这边PC端依然能正常访问，可能DNS出问题了，报错是因为SSL证书验证失败。（不过虽然网站关闭了，但它的API依然能正常访问🤣）

**Pull request closed without merging**
