### PR TITLE
添加扩展

### PR DESCRIPTION
**Pull request by 821938089**

### CODE REVIEW

**Comment by OshekharO** [comment]
How about making extension for mx-player and Desicinemas? you already have made for cs3 before.

**Comment by 821938089** [comment]
@OshekharO 
mxplayer needs to get a parameter in the response header, which is currently not possible in miru.
Desicinemas relies on cs3 video extractor, this part of the port is very troublesome, there is also currently in miru to deal with html is very troublesome, and does not provide good use of the api, and there are some bugs.

**Comment by OshekharO** [comment]
> @OshekharO mxplayer needs to get a parameter in the response header, which is currently not possible in miru. Desicinemas relies on cs3 video extractor, this part of the port is very troublesome, there is also currently in miru to deal with html is very troublesome, and does not provide good use of the api, and there are some bugs.

Hmm, i thought so how about adding some lightnovel and manga website.

**Comment by MiaoMint** [comment]
是不是有点重复的了，只是改了api的 也许可以做个设置？ ，待会儿我处理下。

**Comment by MiaoMint** [comment]
哦不对 应该用筛选 。

**Comment by MiaoMint** [comment]
image
好像都没问题 ，把多余的删除了？ 这种有点污染仓库

**Comment by OshekharO** [comment]
author is not Hour it's Horis

**Comment by 821938089** [comment]
还差个八戒影视，那个是xml的
海外看影视的搜索需要特殊处理

这个筛选是可以按源分类来显示吗？就是之前那种一个一个的显示方式
有没有二级筛选？这些源他也提供了一个分类

**Comment by MiaoMint** [comment]
> 还差个八戒影视，那个是xml的 海外看影视的搜索需要特殊处理
> 
> 这个筛选是可以按源分类来显示吗？就是之前那种一个一个的显示方式 有没有二级筛选？这些源他也提供了一个分类

同样的代码就放一起吧 二级筛选可以做 都做判断就行了 还有 search 有第三个 参数 就是和这个方法一样的就是选择的项

```js
createFilter(filter) {
    const six = {
      title: "性别",
      max: 1,
      min: 1,
      default: "all",
      options: {
        all: "全部",
        boy: "男生",
        girl: "女生",
      },
    };
    if (filter && filter.six[0] == "boy") {
      return {
        six,
        category: {
          title: "类别",
          max: 2,
          min: 1,
          default: "all",
          options: {
            all: "全部",
            action: "热血",
            adventure: "冒险",
            fantasy: "奇幻",
            comedy: "喜剧",
            drama: "战斗",
            horror: "恐怖",
          },
        },
      };
    }
    return {
      six,
      category: {
        title: "类别",
        max: 2,
        min: 1,
        default: "all",
        options: {
          all: "全部",
          action: "热血",
          adventure: "冒险",
          fantasy: "奇幻",
          comedy: "喜剧",
          drama: "战斗",
          horror: "恐怖",
          mystery: "悬疑",
          romance: "爱情",
          scifi: "科幻",
          sliceoflife: "日常",
          thriller: "推理",
          yuri: "百合",
          yaoi: "耽美",
          mecha: "机战",
          sports: "体育",
        },
      },
    };
  }
```

**Comment by MiaoMint** [comment]
你把一样的删了吧

**Comment by 821938089** [comment]
好了

**Pull request merged**
