### PR TITLE
Create flimypujab.com.js

### PR DESCRIPTION
**Pull request by appdevelpo**

### CODE REVIEW

**Comment by OshekharO** [comment]
Screenshot_2023-10-10-10-40-12-48_724c77a6924735f59ad9bef5bae520c3

**Comment by OshekharO** [comment]
Screenshot_2023-10-10-10-46-38-97_724c77a6924735f59ad9bef5bae520c3
Screenshot_2023-10-10-10-40-12-48_724c77a6924735f59ad9bef5bae520c3

**Comment by appdevelpo** [comment]
> Screenshot_2023-10-10-10-46-38-97_724c77a6924735f59ad9bef5bae520c3 Screenshot_2023-10-10-10-40-12-48_724c77a6924735f59ad9bef5bae520c3

where did you met the error

**Comment by OshekharO** [comment]
Ok, it's isp issue had to use VPN

**Pull request merged**
