### PR TITLE
add: GakiArchives

### LINKED ISSUE #114: GakiArchives
### Source name

GakiArchives

### Source URL

https://www.gakiarchives.com

### Package type

bangumi

### Source language

en, jp

### Other details

A fan supported collections of Gaki no Tsukai, The 24 Hour No Laughing Batsu Game, and other similar/related shows, maintained by The Silent Library.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

### PR DESCRIPTION
**Pull request by bachig26**
Closes #114 

@OshekharO since there is no cover and description in the video/detail page, i have commented it out.

but for description, i wanted to add the text from category/season name in the `class = "far fa-folder"`, i'm confused on how to fetch it since it's not inside the block, i don't how to get it. if you please fix them for me. thanks.

### CODE REVIEW

**Comment by OshekharO** [comment]
Class li far fa-folder this is empty where is the information in it or any text?

**Comment by bachig26** [comment]
> Class li far fa-folder this is empty where is the information in it or any text?

view-source:gakiarchives.com/video/40
line 162: 1`<i class="far fa-folder"></i> <a href="[/category/15](https://gakiarchives.com/category/15)">Detectives (2015)</a>`

**Comment by OshekharO** [comment]
You want to capture this Detectives (2015)?

**Comment by bachig26** [comment]
> You want to capture this Detectives (2015)?

yes

**Comment by OshekharO** [comment]
Try this

.far.fa-folder > a or i.far.fa-folder > a ( try both )

desc: desc.trim(),

**Comment by OshekharO** [comment]
Worked?

**Comment by bachig26** [comment]
> Try this
> 
> .far.fa-folder > a or i.far.fa-folder > a ( try both )
> 
> desc: desc.trim(),

no, both doesn't work.

also i just checked cover isn't working with the update.
miru_IP4EuhKqiH

**Comment by OshekharO** [comment]
Check logs for cover and send pic

**Comment by bachig26** [comment]
> Check logs for cover and send pic

it doesn't have any info for cover...
miru_nWuZhsjsBB

actually the regex works but doesn't display the cover in app.

**Pull request merged**
